appstore/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from apps import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'accounts/',include('users.urls')),
    path(r'',          views.apps_default, name='default-page'),
    path(r'apps/',       include('apps.urls')),
    # path(r'search',      include('haystack.urls')),
    path(r'search', views.custom_search_query, name='search'),
    path(r'download/',   include('download.urls')),
    path(r'submit_app/', include('submit_app.urls')),
    path(r'users/',      include('users.urls')),
    path(r'help/',       include('help.urls')),
    path(r'backend/',    include('backend.urls')),
    path(r'obr/', include('obr.urls')),
    path(r'community_fav/<int:page>/', views.apps_default),
    re_path(r'installapp/(.+)', views.install_app, name='install-app')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# see https://docs.djangoproject.com/en/2.1/howto/static-files/

obr/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('pending_releases/', views.redirect_page),
    path('pending_releases/repository.xml', views.serve_file_pending),
    path('releases/', views.redirect_page),
    path('releases/repository.xml', views.serve_file_released)
]

apps/models.py
import hashlib
import re
from os.path import join as pathjoin
from urllib.parse import urljoin

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.urls import reverse

class App(models.Model):
    Bundle_Name         = models.CharField(max_length=127, unique=True)
    Bundle_SymbolicName = models.CharField(max_length=127, unique=True)

    editors             = models.ManyToManyField(User, blank=True)

    stars               = models.PositiveIntegerField(default=0)

    def is_editor(self, user):
        if not user:
            return False
        if user.is_staff or user.is_superuser:
            return True
        return user in self.editors.all()

    def __str__(self):
        return self.Bundle_Name

    @property
    def stars_percentage(self):
        return 100 * self.stars / 5

    @property
    def page_url(self):
        return reverse('app_page', args=[self.Bundle_SymbolicName])

    search_schema = ('^Bundle_Name')
    search_key = 'name'

    def __unicode__(self):
        return self.Bundle_Name


@receiver(models.signals.pre_delete, sender=App)
def delete_file(sender, instance, *args, **kwargs):
    """ Deletes Release files on `post_delete` """
    if instance.release_file:
        instance.release_file.delete()
    if instance.logo:
        instance.logo.delete()


class Author(models.Model):
    name        = models.CharField(max_length=255)
    institution = models.CharField(max_length=255, null=True, blank=True)

    search_schema = ('name', 'institution')
    search_key = 'id'

    def __unicode__(self):
        if not self.institution:
            return self.name
        else:
            return self.name + ' (' + self.institution + ')'


VersionRE = re.compile(r'^(\d+)(?:\.(\d)+)?(?:\.(\d)+)?(?:\.([\w-]+))?$')


def release_file_path(release, filename):
    return pathjoin(release.app.Bundle_SymbolicName, 'releases', release.Bundle_Version, release.app.Bundle_SymbolicName + '-' +
                    release.Bundle_Version + '.jar')


def logo_path(release, filename):
    get_ext = filename.split('.')[-1]
    return pathjoin(release.app.Bundle_SymbolicName, 'releases', release.Bundle_Version, release.app.Bundle_SymbolicName + '-' +
                    release.Bundle_Version + '.' + get_ext)


GENERIC_LOGO_URL = urljoin(settings.STATIC_URL, 'apps/img/app_icon_generic.png')


class Release(models.Model):
    app                     = models.ForeignKey(App, on_delete=models.CASCADE)
    Bundle_Version          = models.CharField(max_length=31)
    short_title             = models.CharField(max_length=255, blank=True, null=True)
    Bundle_Description      = models.TextField(blank=True, null=True)

    license_url             = models.URLField(blank=True, null=True)
    license_confirm         = models.BooleanField(default=False)

    website_url             = models.URLField(blank=True, null=True)
    tutorial_url            = models.URLField(blank=True, null=True)
    citation                = models.CharField(max_length=31, blank=True, null=True)
    code_repository_url     = models.URLField(blank=True, null=True)

    contact_email           = models.EmailField(blank=True, null=True)

    platform_compatibility  = models.CharField(max_length=31)
    created                 = models.DateTimeField(auto_now_add=True)
    active                  = models.BooleanField(default=True)
    logo                    = models.ImageField(blank=True, null=True, upload_to=logo_path)

    repository_xml          = models.TextField(blank=True, null=True)  # OBR Index Repository XML
    release_file            = models.FileField(upload_to=release_file_path)

    hexchecksum             = models.CharField(max_length=511, blank=True, null=True)

    stars = models.PositiveIntegerField(default=0)

    uploader_ip = models.GenericIPAddressField(null=True)

    authors                 = models.ManyToManyField(Author, blank=True, through='OrderedAuthor')

    # To Display Release App and its version on Admin Panel > Releases Tab
    def __str__(self):
        return self.app.Bundle_Name + " - " +  self.Bundle_Version

    @property
    def ordered_authors(self):
        return (a.author for a in OrderedAuthor.objects.filter(release=self))

    @property
    def version_tuple(self):
        matched = VersionRE.match(self.Bundle_Version)
        if not matched:
            return None
        (major, minor, patch, tag) = matched.groups()
        major = int(major)
        minor = int(minor) if minor else None
        patch = int(patch) if patch else None
        return major, minor, patch, tag

    @property
    def created_iso(self):
        return self.created

    @property
    def release_file_url(self):
        return self.release_file.url if self.release_file else None

    @property
    def release_download_url(self):
        return reverse('release_download', args=[self.app.Bundle_SymbolicName, self.Bundle_Version])

    @property
    def logo_url(self):
        return self.logo.url if self.logo else GENERIC_LOGO_URL

    def __unicode__(self):
        return self.app.Bundle_Name + ' ' + self.Bundle_Version

    def calc_checksum(self):
        cs = hashlib.sha512()
        f = self.release_file.file
        f.open('rb')
        while True:
            buf = f.read(128)
            if not buf: break
            cs.update(buf)
        f.close()
        self.hexchecksum = '%s:%s' % (cs.name, cs.hexdigest())
        self.save()

    def delete_files(self):
        self.release_file.delete()

    def delete_logo(self):
        self.logo.delete()

    class Meta:
        ordering = ['-created']

    search_schema = ('^Bundle_Name', 'short_title', 'Bundle_Description')
    search_key = 'name'


def screenshot_path(screenshot, filename):
    get_ext = filename.split('.')[-1]
    return pathjoin(screenshot.release.app.Bundle_SymbolicName, 'releases', screenshot.release.Bundle_Version, 'screenshots',
                    filename + '_' +screenshot.release.app.Bundle_SymbolicName + '-' + screenshot.release.Bundle_Version + '.' + get_ext)


def thumbnail_path(screenshot, filename):
    get_ext = filename.split('.')[-1]
    return pathjoin(screenshot.release.app.Bundle_SymbolicName, 'releases', screenshot.release.Bundle_Version, 'thumbnails',
                    filename + '_' +screenshot.release.app.Bundle_SymbolicName + '-' + screenshot.release.Bundle_Version + '.' + get_ext)


class Screenshot(models.Model):
    release        = models.ForeignKey(Release, on_delete=models.CASCADE)
    screenshot = models.ImageField(upload_to=screenshot_path)
    thumbnail  = models.ImageField(upload_to=thumbnail_path)

    def __unicode__(self):
        return '%s - %d' % (self.app.Bundle_Name, self.id)


@receiver(models.signals.pre_delete, sender=Release)
def delete_file(sender, instance, *args, **kwargs):
    """ Deletes Release files on `post_delete` """
    if instance.release_file:
        instance.release_file.delete()
    if instance.logo:
        instance.logo.delete()


class OrderedAuthor(models.Model):
    author       = models.ForeignKey(Author, on_delete=models.CASCADE)
    release          = models.ForeignKey(Release, on_delete=models.CASCADE)
    author_order = models.PositiveSmallIntegerField(default=0)

    def __unicode__(self):
        return unicode(self.author_order) + ': ' + self.app.Bundle_Name + ' by ' + self.author.name

    class Meta:
        ordering = ["author_order"]

apps/templates/apps/all_apps.html
{% extends "apps/nav_panel.html" %}
{% load static %}
{% load app_buttons %}

{% block title %}
 - All Apps
{% endblock %}

{% block main %}
    {% list_of_apps apps releases %}
{% endblock %}

apps/templates/apps/app_button.html
{% load static %}
{% load title_modified %}
<div class="box-part app_button"
        order_index="{{ order_index }}"
        Bundle_Name="{{ app.Bundle_Name }}"
        downloads="{{ total_download }}"
        created="{{ release.created_iso|date:'j M, H:i:s' }}"
        curated_category="{{ curated_categories }}"
        onClick="window.location='{% url 'app_page' app.Bundle_SymbolicName %}';">
    <div class="row">
        <div class="col-md-12 mt-2 mb-3">
            <span class="tile-legend head_cc"></span>
        </div>
        <div class="col-md-12">
            <span class="true-divide">
                <img src="{{ release.logo_url }}" class="custom-img">
            </span>
            <span class="right-divide ml-3">
                <h5 class="app-button-title mr-3">{{ app.Bundle_Name | truncatechars:40 }}</h5>
                {% if release.authors.all|get_authors != '' %}
                    <p class="authored mr-3"> by {{ release.authors.all|get_authors }}</p>
                {% endif %}
                {% if release.short_title %}
                <div class="desc-spaced mr-3">
                    <p class="mt-2">{{ release.short_title }}</p>
                </div>
                {% endif %}
                {% if not release.short_title %}
                    <h6 class="desc-box small-visible" style="visibility: hidden;">No Description</h6>
                {% endif %}
            </span>
        </div>
    </div>
</div>

apps/templates/apps/app_buttons.html
{% load app_buttons %}

<div class="row">
    {% for app in releases %}
        <div class="col-lg-4 col-md-6 col-xs-12 app-tile-col pl-0 mb-3">
        {% app_button app forloop.counter releases %}
        </div>
    {% endfor %}
</div>

apps/templates/apps/app_page.html
{% extends "base.html" %}
{% load static %}
{% load markdown %}
{% load timestamp_converter %}
{% load title_modified %}
{% load i18n %}
{% import logging

# Get an instance of a logger
logger = logging.getLogger("apps/app_page.html") %}

{% block more_head %}
<!-- Screenshot Popup Box and Fontawesome libraries -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" integrity="sha256-HAaDW5o2+LelybUhfuk0Zh2Vdk8Y2W2UeKmbaXhalfA=" crossorigin="anonymous" />

<!-- Custom Css libraries -->
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_page.css" />
<link rel="stylesheet" type="text/css" media="all" href="{% get_static_prefix %}apps/css/app_stars.css" />
{% endblock %}

{% block title %}- {{ app.Bundle_Name }}{% endblock %}

{% block content %}

{% csrf_token %}
<br />
{# App header #}
<div class="col-md-12">
	{# App Name and Icon #}
	<div class="row">
		<div class="col-md-9">
			<div class="row">
				<div class="col-md-2 img-div" style="background-image: url('{{latest_released.logo_url}}');background-size: contain;"></div>
				<div class="col-md-8">
					{# App Name and description #}
					<h2 class="app-name" id="app-name">
						{{ app.Bundle_Name }}
					</h2>
					<span class="app-def-desc">{% if latest_released.short_title %}{{ latest_released.short_title }}{% endif %}</span>
					<br />
					{# Ratings #}
					<span class="get-app-stars">{{ app.stars_percentage }}</span>
					<x-star-rating data-authenticated="{{ is_logged_in }}"></x-star-rating>
					{# End Ratings #}
					{# Downloads #}
					<span class="app-usage-info-divider"></span>
					{{ download_count }}
					<a href="{% url 'app_stats' app.Bundle_SymbolicName %}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Click to view the download stats.">
						 Downloads
					</a>
					{# End Downloads #}

					{# Helpdesk #}
					<span> | </span>
					<a href="https://groups.google.com/forum/?fromgroups#!searchin/integrated-genome-browser-help-desk/{{ app.Bundle_Name }}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Search IGB Helpdesk for questions about this app.">Helpdesk</a>
					{# End Helpdesk #}
					{# App usage info (ratings, downloads, helpdesk, citations, discussions) #}
					{% if latest_released.citation or  latest_released.code_repository_url %}
					{# Citations #}
					{% if latest_released.citation %}
					<span> | </span>
					<a href="https://www.ncbi.nlm.nih.gov/pubmed?linkname=pubmed_pubmed_citedin&from_uid={{ latest_released.citation }}" target="_blank" class="has-tooltip" data-toggle="tooltip" data-title="Search PubMed for articles citing this app.">{% trans "  Citations" %}</a>

					{% endif %}
					{# End Citations #}
					<span class="app-usage-info-divider"></span>

					{% if latest_released.code_repository_url %}
					<a href="{{ latest_released.code_repository_url }}" target="_blank">
						<img src="{% get_static_prefix %}apps/img/open-source.png" class="has-tooltip" data-toggle="tooltip" data-title="This app is open source.">
					</a>
					{% endif %}
					{# end badges #}

					{% endif %}
					{# End app usage info #}
				</div>
			</div>
			<div class="row mt-3">
					<div class="col-md-12">
					<!-- Nav tabs -->
					<ul class="nav nav-tabs" id="myTab" role="tablist">
						<li class="nav-item">
							<a class="nav-link pl-2 pr-2 text-dark font-weight-bold active" id="app-details-tab" data-toggle="tab" href="#app-details" role="tab" aria-controls="app-details" aria-selected="true">Overview</a>
						</li>
						<li class="nav-item">
							<a class="nav-link pl-2 pr-2 text-dark font-weight-bold" id="app-releases-tab" data-toggle="tab" href="#app-releases" role="tab" aria-controls="app-releases" aria-selected="false">Release History</a>
						</li>
					</ul>
					<!-- Tab panes -->
					<div class="tab-content">
						<div class="tab-pane active" id="app-details" role="tabpanel" aria-labelledby="app-details-tab">
						<!-- App Version #} -->
							<div class="row mt-4" style="font-size: large">
								<div class="col-md-12 font-weight-bold">
									Version:    {{ latest_released.Bundle_Version }}
								</div>
							</div>

							{# Screenshots #}
							{% if latest_released.screenshot_set.all %}
							<div class="row">
								<div class="col-md-12 mt-3" id="app-screenshots">
									<p class="font-weight-bold mb-3">Screenshots:</p>
									{% for screenshot in latest_released.screenshot_set.all %}
									<a href="{{ screenshot.screenshot.url }}" data-toggle="lightbox" data-gallery="screen-gallery">
										<img src="{{ screenshot.thumbnail.url }}" class="img-fluid"/>
									</a>
									{% endfor %}
								</div>
							</div>
							{% endif %}
							{# End Screenshots #}

							<br />

							{# Details #}
							{% if decoded_details %}
							<div class="row">
								<div class="col-md-12" id="app-details-md">
									{{ decoded_details | markdown_parser | safe }}
								</div>
							</div>
							{% endif %}
							{# End Details #}

							{# Authors #}
							{% if latest_released.authors.all %}
							<div class="row">
								<div class="col-md-8">
									<span class="font-weight-bold">Authors:</span>
									<ul>
										{% for author in latest_released.ordered_authors %}
										<li>
											<a href="{% url 'author_page' author.name %}">
												{{ author.name }} {% if author.institution %} ({{ author.institution }}){% endif %}
											</a>
										</li>
										{% endfor %}
									</ul>
								</div>
							</div>
							{% endif %}
							{# End Authors #}
						</div>
					<div class="tab-pane" id="app-releases" role="tabpanel" aria-labelledby="app-releases-tab">
						{% for release in released_apps %}
							<div class="row">
								<div class="col-md-12">
									<div class="row">
										<div class="col-md-3 img-div" style="background-image: url('{{release.logo_url}}');background-size: contain; margin-top: 30px;"></div>
										<div class="col-md-9">
											{# Release version #}
											<br />
											{% if forloop.first %}
												<h5>
													Current Version :
													<!-- Removed release.version argument href="% url 'release_download' app.name %-->
													{{ release.Bundle_Version }}
												</h5>
											{% else %}
												<h5>
													Version :
													<!-- Removed release.version argument href="% url 'release_download' app.name %-->
													{{ release.Bundle_Version }}
												</h5>
											{% endif %}
											<p><strong>Release Date : </strong> {{ release.created_iso|date:"j M, Y" }}</p>
											{# End Release version #}

											{# Works with #}
											<p>
												<strong>Works with</strong> IGB
												{{ release.platform_compatibility | strip_double_quotes}}
											</p>
										</div>
									</div>
									<hr />
								</div>
							</div>
							{% endfor %} {# end looping thru each release #}
						</div>
					</div>
					</div>
			</div>
		</div>
		<div class="col-md-3">
			{# Editor menu #}
			{% if is_editor %}
			<div class="btn-group mt-5 mb-3">
				<button class="btn btn-lg btn-warning" onclick="document.location.href='{% url 'app_page_edit' app.Bundle_SymbolicName %}';">
					<i class="fa fa-pencil text-white"></i>
					&nbsp;<small class="font-weight-bold text-dark">Edit this page</small>
				</button>
			</div>
			{% endif %}
			{# End editor menu #}
			{# Right-hand panels #}
			{# 3.0 download panel #}
			<div class="box-release-info mt-1" id="app_status_block">
				<h6 align="center" class="panel-title text-muted">To install and run this App, start IGB! Then come back and refresh this page.</h6>
				<a href="https://bioviz.org" id="change-url">
				<button class="btn btn-block btn-info pt-3 mb-2" id="app-install-btn">
					{# <-- download button icon will go here #}
					<h6 class="font-weight-bold"><i class="fa fa-download"></i>&nbsp;&nbsp;&nbsp;Get latest IGB</h6> {# <-- download button text will go here #}
				</button>
				</a>
				<p class="mb-2" id="app_version"></p>
				{% if app.license_url %}
				<strong>License</strong> <a href="{{ app.license_url }}" target="_blank">Click here</a>
				<br />
				{% endif %}
				<strong> App Version </strong> {{ latest_released.Bundle_Version }}<br />
				<strong id="igb_version">Works with IGB</strong> {{ latest_released.platform_compatibility | strip_double_quotes}}
			</div>

			{# end 3.0 download panel #}

			{# latest_released resources #}
			<div class="alert alert-warning box-resource">
				<h5 class="font-weight-bold">RESOURCES</h5>
				<ul class="nav nav-list inline-list">
					<li>
						<i class="fa fa-question-circle"></i>
						<a class="text-dark" href="https://groups.google.com/forum/#!forum/integrated-genome-browser-help-desk" target="_blank">
							Ask a question
						</a>
					</li>

					<li>
						<i class="fa fa-comments"></i>
						<a class="text-dark" href="https://groups.google.com/forum/?fromgroups#!searchin/integrated-genome-browser-help-desk/{{ app.Bundle_Name }}" target="_blank">
							Search helpdesk
						</a>
					</li>

					{% if latest_released.website_url %}
					<li>
						<i class="fa fa-home"></i>
						<a class="text-dark" href="{{ latest_released.website_url }}" target="_blank" style="padding-right:50px;">
							Website
						</a>
					</li>
					{% endif %}

					{% if latest_released.tutorial_url %}
					<li>
						<i class="fa fa-book"></i>
						<a class="text-dark" href="{{ latest_released.tutorial_url }}" target="_blank" style="padding-right:50px;">
							Tutorial
						</a>
					</li>
					{% endif %}

					{% if latest_released.citation %}
					<li>
						<i class="fa fa-heart"></i>
						<a class="text-dark" href="http://www.ncbi.nlm.nih.gov/pubmed/{{ latest_released.citation }}" target="_blank" style="padding-right:50px;">
							Cite this App
						</a>
					</li>
					{% endif %}

					{% if latest_released.code_repository_url %}
					<li>
						<i class="fa fa-code-fork"></i>
						<a class="text-dark" href="{{ latest_released.code_repository_url }}" target="_blank">
							Code Repository
						</a>
					</li>
					{% endif %}

					{% if latest_released.contact_email %}
					<li>
						<i class="fa fa-envelope"></i>
						<a class="text-dark" href="mailto:{{ latest_released.contact_email }}" target="_blank" style="padding-right:50px;">
							 E-mail
						</a>
					</li>
					{% endif %}
				</ul>
			</div>
			{# end latest_released resources #}
		</div>
		</div>
		{# End app header #}
	</div>
</div>
<br />
{# Main app page content #}
</div>
{# end main app page content #}

{# Delete all ratings modal dialog #}
<div class="modal fade" role="dialog" id="delete_ratings_modal">
	<div class="modal-dialog" role="document">
    	<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Delete All Ratings</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<p>Are you sure you want to delete all of your app's ratings?</p>
			</div>
			<div class="modal-footer">
				<form target="" method="post" style="margin: 0;">
					{% csrf_token %}
					<input type="hidden" name="action" value="ratings_delete_all">
					<a href="#" class="btn" data-dismiss="modal">Cancel</a>
					<input type="submit" class="btn btn-danger" value="Yes, I'm Sure">
				</form>
			</div>
		</div>
	</div>
</div>
{# End modal dialog #}

{# License modal dialog #}
{% if latest_released.license_confirm and latest_released.license_url %}
<div class="modal hide fade in" id="license_modal">
	<div class="modal-header">
		<a class="close" data-dismiss="modal">&times;</a>
		<h3>License Agreement</h3>
	</div>
	<div class="modal-body">
		<iframe data-src="{{ latest_released.license_url }}" width="500" height="400"></iframe>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn" data-dismiss="modal">Don't Accept</a>
		<a href="#" class="btn btn-primary">Accept</a>
	</div>
</div>
{% endif %}
{# End license modal dialog #}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.min.js" integrity="sha256-Y1rRlwTzT5K5hhCBfAFWABD4cU13QGuRN6P5apfWzVs=" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% get_static_prefix %}apps/js/app_page.js"></script>

<script>
	$(document).on('click', '[data-toggle="lightbox"]', function(event) {
		event.preventDefault();
		$(this).ekkoLightbox();
	});
</script>

<script type="text/javascript">
	if(!AppPage.isSafari()){
		AppPage.setup_install("{{ app.Bundle_Name | escapejs }}", "{{ app.Bundle_SymbolicName | escapejs }}",  "{{ repository_url | escapejs }}", "{{ latest_released.Bundle_Version | escapejs }}");

		{% if latest_released.Bundle_Description %}
		AppPage.setup_details();
		{% endif %}
	}
	// Javascript to enable link to tab
	var url = document.location.toString();
	if (url.match('#')) {
		$('.nav-tabs a[href="#' + url.split('#')[1] + '"]').tab('show');
	}

</script>
{% endblock %}

</div>

{% block footer %}
	<!-- Markdown Library -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.2/marked.min.js"></script>
    <script type="text/javascript" src="{% get_static_prefix %}apps/js/star_rating.js"></script>
{% endblock %}

apps/templates/apps/apps_default.html
{% extends "apps/nav_panel.html" %}
{% load app_buttons %}

{% block main %}

<div class="row">
    <div class="col-lg-12">
        {% app_buttons downloaded_apps_pg releases %}
    </div>
</div>

{% endblock %}

apps/templates/apps/apps_with_author.html
{% extends "apps/nav_panel.html" %}
{% load app_buttons %}

{% block title %}
- {{ author_name }}
{% endblock %}

{% block main %}
<div class="col-md-12">
    <h2>Apps by: {{ author_name }}</h2>
</div>

<div class="col-lg-12">
    {% app_buttons apps releases %}
</div>
{% endblock %}

apps/templates/apps/apps_with_tag.html
{% extends "apps/nav_panel.html" %}
{% load app_buttons %}

{% block title %}
- {{ tag.fullname }} category
{% endblock %}

{% block main %}
  {% list_of_apps apps releases%}
{% endblock %}

apps/templates/apps/list_of_apps.html
{% load static %}
{% load app_buttons %}

<div class="row spaced" id="apps-with-releases">
    <div class="col-md-12">
        <table style="margin-bottom: 1em;">
            <tr>
            <td><span style="margin-right: 0.5em;">Sort by</span></td>
            <td>
                <span id="sort_app_buttons" class="btn-group">
                    {% for button_name, attr_name, attr_type in sort_criteria %}
                    <button class="btn bg-light" attr_name="{{ attr_name }}" attr_type="{{ attr_type }}">
                        <span class="title">{{ button_name | title }}</span>
                        <span class="triangle"></span>
                    </button>
                    {% endfor %}
                </span>
            </td>
        </tr>
        </table>
    </div >
    <div class="col-md-12">
        {% if apps_with_releases %}
            {% app_buttons apps_with_releases releases %}
        {% endif %}
    </div>
</div>

<script type="text/javascript" src="{% get_static_prefix %}apps/js/sort_app_buttons.js"></script>
<script type="text/javascript">
    $(function() {
        SortAppButtons.init_sort_buttons($('#apps-with-releases'));
    });
</script>
 

apps/templates/apps/list_of_apps_search.html
{% load static %}
{% load app_buttons %}

{% if apps_with_releases %}
{% app_buttons apps_with_releases releases %}
{% endif %}

apps/templates/apps/search_panel.html
{% extends "apps/nav_panel.html" %}